---
title: "Relationship between GDP, Life Expectancy, and CO2 Emissions"
author: "Calla Bush St George"
date: "2023-01-18"
output: html_document
md_document:
  variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
```


```{r data}
gapminder_1997 <- read_csv("un-report/data/gapminder_1997.csv")
```
```{r GDP-lifeExp-1997-plot, echo = FALSE, fig.width=4, fig.height=3,    fig.align='center'}
#Make plot of gdp(x-axis) vs LifeExp (y-axis)
ggplot(gapminder_1997, aes(x=gdpPercap, y=lifeExp)) +
  geom_point() +
      labs(x="GDP",
           y="Life Expectanct",
           title="There is a strong association between a nation's GDP and Life Expectancy"
      ) 

```

```{r basic-country-stats}
#Number of countries in the dataset
  gapminder_1997 %>%
  select(country)%>%
  n_distinct()

#minimum GDP
minGDP <- gapminder_1997 %>%
  summarize(round(min(gdpPercap))) %>%
  pull()

#maximum GDP
minGDP <- gapminder_1997 %>%
  summarize(round(max(gdpPercap))) %>%
  pull()
```

The number of countries in the dataset is `nCountries`.
The minimum GDP is `minGDP`.
The maximum GDP is `maxGDP`.
